### ISSUE TITLE
cannot retrieve root ca certificate from pki/ca or pki/ca/pem

### ISSUE THREAD

**Issue by dansteen** [hashicorp/vault-ruby#116]
I'm using vault 0.6.2, and when I try to retrieve the root certificate, I am not able to:
```
vault.logical.read('pki/ca')
NoMethodError: undefined method `each' for #<String:0x0000000205ded8>
        from /home/dsteen/.gem/ruby/2.3.0/gems/vault-0.6.0/lib/vault/response.rb:49:in `initialize'
        from /home/dsteen/.gem/ruby/2.3.0/gems/vault-0.6.0/lib/vault/response.rb:38:in `new'
        from /home/dsteen/.gem/ruby/2.3.0/gems/vault-0.6.0/lib/vault/response.rb:38:in `decode'
        from /home/dsteen/.gem/ruby/2.3.0/gems/vault-0.6.0/lib/vault/api/logical.rb:48:in `read'
        from (irb):56
        from /usr/bin/irb:11:in `<main>'
```
The same happens if i try to use the `pki/ca/pem` endpoint.   As a note,  I have the same issue with the vault cli client (though a different error):
```
~/vault read 'pki/ca'                                                
Error reading pki/ca: json: cannot unmarshal number into Go value of type api.Secret
```
Or, if I use `pki/ca/pem` I get:
```
~/vault read 'pki/ca/pem'                                              
Error reading pki/ca/pem: invalid character '-' in numeric literal
```
Do you want me to open a separate issue for the cli?

**Comment by gopisaba** [comment]
I have similar issue with `vault.logical` as well

```
client.logical.read("secret/app/ssh_pub", options = {})
NoMethodError: undefined method `each' for #<String:0x000000021ce8d0>
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.7.3/lib/vault/response.rb:49:in `initialize'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.7.3/lib/vault/response.rb:38:in `new'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.7.3/lib/vault/response.rb:38:in `decode'
	from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.7.3/lib/vault/api/logical.rb:48:in `read'
	from (irb):163
	from /opt/chef/embedded/bin/irb:11:in `<main>'
```

Looks like [json = client.get("/v1/#{encode_path(path)}", {}, headers)](https://github.com/hashicorp/vault-ruby/blob/347589d7ecad480827856115bcf613d38a42744a/lib/vault/api/logical.rb#L47), outputs sometime as hash and sometime as json.

**Comment by jefferai** [comment]
@dansteen as the docs for that endpoint state, it returns raw data, so that clients referencing the authority URL in issues certs get back a der blob as expected. Working as intended...
