### ISSUE TITLE
Vault.logical.read throws NoMethodError when Vault responds with HTTP 204 (No Content)

### ISSUE THREAD

**Issue by wfhartford** [hashicorp/vault-ruby#241]
When the `Vault.logical.read` function is called and Vault responds with a HTTP 204 No Content response, a NoMethodError is thrown by the vault client:
```
/usr/local/bundle/gems/vault-0.14.0/lib/vault/response.rb:49:in `initialize': undefined method `each' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/vault-0.14.0/lib/vault/response.rb:38:in `new'
	from /usr/local/bundle/gems/vault-0.14.0/lib/vault/response.rb:38:in `decode'
	from /usr/local/bundle/gems/vault-0.14.0/lib/vault/api/logical.rb:48:in `read'
```

In my case, I was requesting the `/pki/ca` where `pki` is the path of a newly mounted PKI secret engine whose signing certificate has not been created.

The `Logical.read` function calls `client.get` which returns `nil` when the server responds with 204. This `nil` value gets passed to `Secret.decode` from which the NoMethodError is thrown.

**Comment by wfhartford** [comment]
The work around I've used is to call `client.get` directly and check for `nil`.

**Comment by avdi** [comment]
Can confirm, also seeing this
