### ISSUE TITLE
TLS1_2_VERSION errors since updating to 0.18.0

### ISSUE THREAD

**Issue by oberones** [hashicorp/vault-ruby#299]
The recent changes to accommodate TLS 1.3 seem to have caused a regression in TLS 1.2. We started seeing the following errors from clients using the latest 0.18.0 gem:

```
NameError: uninitialized constant OpenSSL::SSL::TLS1_2_VERSION
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.18.0/lib/vault/client.rb:116:in `block in pool'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.18.0/lib/vault/client.rb:85:in `synchronize'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.18.0/lib/vault/client.rb:85:in `pool'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.18.0/lib/vault/client.rb:282:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.18.0/lib/vault/client.rb:199:in `post'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/vault-0.18.0/lib/vault/api/auth.rb:98:in `approle'
```

**Comment by dhuckins** [comment]
looking in to, can you provide a [minimal, reproducible example ](https://stackoverflow.com/help/minimal-reproducible-example) so we can look into further please?

**Comment by sudomateo** [comment]
Sorry about that! Ruby 2.3 doesn't include the `OpenSSL::SSL::TLS1_2_VERSION` constant. I'll get this updated to account for that. Thank you for reporting this!

```
> docker run -it ruby:2.3 bash
root@fc4fd758ab36:/# irb
irb(main):001:0> require 'openssl'    
=> true
irb(main):002:0> OpenSSL::SSL.constants
=> [:SSLError, :SSLErrorWaitReadable, :SSLErrorWaitWritable, :Session, :SSLContext, :SSLSocket, :VERIFY_NONE, :VERIFY_PEER, :VERIFY_FAIL_IF_NO_PEER_CERT, :VERIFY_CLIENT_ONCE, :OP_MICROSOFT_SESS_ID_BUG, :OP_NETSCAPE_CHALLENGE_BUG, :OP_NETSCAPE_REUSE_CIPHER_CHANGE_BUG, :OP_SSLREF2_REUSE_CERT_TYPE_BUG, :OP_MICROSOFT_BIG_SSLV3_BUFFER, :OP_MSIE_SSLV2_RSA_PADDING, :OP_SSLEAY_080_CLIENT_DH_BUG, :OP_TLS_D5_BUG, :OP_TLS_BLOCK_PADDING_BUG, :OP_DONT_INSERT_EMPTY_FRAGMENTS, :OP_ALL, :OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION, :OP_SINGLE_ECDH_USE, :OP_SINGLE_DH_USE, :OP_EPHEMERAL_RSA, :OP_CIPHER_SERVER_PREFERENCE, :OP_TLS_ROLLBACK_BUG, :OP_NO_SSLv2, :OP_NO_SSLv3, :OP_NO_TLSv1, :OP_NO_TLSv1_1, :OP_NO_TLSv1_2, :OP_NO_TICKET, :OP_NO_COMPRESSION, :OP_PKCS1_CHECK_1, :OP_PKCS1_CHECK_2, :OP_NETSCAPE_CA_DN_BUG, :OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG, :SocketForwarder, :SSLServer]
```

**Comment by oberones** [comment]
Ah good catch! tyty!! Sorry for the sparse details in my report :P

**Comment by sudomateo** [comment]
> Ah good catch! tyty!! Sorry for the sparse details in my report :P

No worries! The logs allowed us to see the Ruby version and do some digging. We released `v0.18.1` to address this. If something else comes up please let us know!

**Comment by oberones** [comment]
> > Ah good catch! tyty!! Sorry for the sparse details in my report :P
> 
> No worries! The logs allowed us to see the Ruby version and do some digging. We released `v0.18.1` to address this. If something else comes up please let us know!

Heck yeah, thank you so much!! Y'all are awesome - as usual. I owe you a beer.

**Comment by sudomateo** [comment]
> > > Ah good catch! tyty!! Sorry for the sparse details in my report :P
> > 
> > 
> > No worries! The logs allowed us to see the Ruby version and do some digging. We released `v0.18.1` to address this. If something else comes up please let us know!
> 
> Heck yeah, thank you so much!! Y'all are awesome - as usual. I owe you a beer.

I'll buy! 🍻
